### ISSUE TITLE
update vsg

### ISSUE THREAD

**Issue by WdsPjm** [tana/lumrapido#1]
Hello! Is there any plan to support the latest version of vsg

**Comment by tana** [comment]
Sorry, this repository is currently not actively developed, and I have no plan to support newer version of VSG.
However, you can build `lumrapido` by using older VSG (around 2021).

**Comment by WdsPjm** [comment]
Why didn't you use vsg's own method to load gltf? Is there a problem? Now I use vsg's own method to parse gltf, but the index is not the same as the official method provided by gltf.
